[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "schemachange.VERSION"}