config-version: 1

root-folder: ./demo/citibike_jinja/scripts
modules-folder: ./demo/citibike_jinja/modules

snowflake-user: {{ env_var('SNOWFLAKE_USER')}}
snowflake-account: {{ env_var('SNOWFLAKE_ACCOUNT')}}
snowflake-role: SCHEMACHANGE_DEMO_DEPLOY
snowflake-warehouse: SCHEMACHANGE_DEMO_WH
snowflake-database: SCHEMACHANGE_DEMO
snowflake-schema: CITIBIKE_DEMO_JINJA_{{ env_var('SCHEMACHANGE_BUILD_ID') }}
change-history-table: "SCHEMACHANGE_DEMO.SCHEMACHANGE.CITIBIKE_DEMO_JNJA_{{ env_var('SCHEMACHANGE_BUILD_ID') }}_CHANGE_HISTORY"
create-change-history-table: true

vars:
  database_name: {{env_var('SNOWFLAKE_DATABASE', 'SCHEMACHANGE_DEMO')}}
  schema_name: {{env_var('SNOWFLAKE_SCHEMA', 'CITIBIKE_DEMO_JINJA')}}
  secrets:
    # not a good example of secrets, just here to demo the secret filtering
    trips_s3_bucket: s3://snowflake-workshop-lab/citibike-trips
    weather_s3_bucket: s3://snowflake-workshop-lab/weather-nyc
