config-version: 1

root-folder: ./demo/basics

snowflake-schema: {{ env_var('MY_TARGET_SCHEMA')}}
change-history-table: "{{ env_var('SNOWFLAKE_DATABASE')}}.{{ env_var('MY_TARGET_SCHEMA')}}.CHANGE_HISTORY"
create-change-history-table: true

vars:
  database_name: {{env_var('SNOWFLAKE_DATABASE')}}
  schema_name: {{env_var('MY_TARGET_SCHEMA')}}
