name: dev-pytest

on:
  push:
    branches:
      - dev
      - "feature/test_demo"
  
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  build:
    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_USER: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_USER }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_ACCOUNT }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest
      - name: Install SnowSQL
        run: echo "installing SnowSQL"
      - name: Setup Citibike Demo
        run: echo SETUP
      - name: Test Citibike Demo
        run: |
          schemachange --config-folder ./demo/citibike
          schemachange --config-folder ./demo/citibike_jinja
      - name: Teardown Citibike Demo
        run: echo "Cleaning up Citibike Demo"
