name: dev-pytest

on:
  push:
    branches:
      - dev
      - release/**  
  
  workflow_dispatch: 

  pull_request:
    types: [opened, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scenario-name: [ 'basics_demo', 'citibike_demo', 'citibike_demo_jinja']
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_USER: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_USER }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_DATABASE: SCHEMACHANGE_DEMO
      SNOWFLAKE_WAREHOUSE: SCHEMACHANGE_DEMO_WH
      SNOWFLAKE_ROLE: SCHEMACHANGE_DEMO_DEPLOY
      #SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_PASSWORD }}
      #SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_ACCOUNT }}
      #SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SCHEMACHANGE_SNOWFLAKE_USER }}
      SCHEMACHANGE_BUILD_ID: ${{ github.run_number }}_${{ strategy.job-index }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest
      - name: Test Schemachange - ${{ matrix.scenario-name }}
        env:
          SCENARIO_NAME: ${{ matrix.scenario-name }}
        run: |
          export MY_TARGET_SCHEMA="${SCENARIO_NAME}_${{ env.SCHEMACHANGE_BUILD_ID }}"
          echo "::group::Setting up ${MY_TARGET_SCHEMA}"
          schemachange --config-folder ./demo/setup/${SCENARIO_NAME}
          echo "::endgroup::"
          echo "::group::Testing Rendering to ${MY_TARGET_SCHEMA}"
          echo "Work in Progress - To be Tested"
          echo "::endgroup::"
          echo "::group::Testing Deployment using ${MY_TARGET_SCHEMA}"
          schemachange --config-folder ./demo/${SCENARIO_NAME}
          echo "::endgroup::"
          echo "::group::Tearing down up ${MY_TARGET_SCHEMA}"
          schemachange --config-folder ./demo/teardown/${SCENARIO_NAME}
          echo "::endgroup::"
