name: master-pytest

on:
  push:
    branches:
      - master
  
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest
      - name: Setup SnowCLI connection file
        run: |
          echo "[connections]" > config.toml
          echo "[connections.myconnection]" >> config.toml
          chmod 0600 config.toml
      - name: Install snowcli
        run: |
          pip install snowflake-cli-labs
      - name: Test Default snowcli connection
        run: |
          snow --version
          echo "::group::Config Contents"
          more config.toml
          echo "::endgroup::"
          snow --config-file config.toml connection test -c myconnection
          echo "Tested SnowCLI connection successfully!"
          echo "Set default connection"
          snow --config-file config.toml connection set-default "myconnection"
      - name: Test Basic Schemachange
        run: |
          snow --config-file config.toml sql -f ./demo/setup/setup_basics_demo.sql
          schemachange --config-folder ./demo/basics
          snow --config-file config.toml sql -f ./demo/teardown/teardown_basics_demo.sql
      - name: Test Citibike Demo
        run: |
          snow --config-file config.toml sql -f ./demo/setup/setup_citibike_demo.sql
          schemachange --config-folder ./demo/citibike
          snow --config-file config.toml sql -f ./demo/teardown/teardown_citibike_demo.sql
      - name: Test Citibike Demo Jinja Template
        run: |
          snow --config-file config.toml sql -f ./demo/setup/setup_citibike_demo_jinja.sql
          schemachange --config-folder ./demo/citibike_jinja
          snow --config-file config.toml sql -f ./demo/teardown/teardown_citibike_demo_jinja.sql
